version: '3.8'

services:
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile.simple
    ports:
      - "8081:8081"
    volumes:
      - ./Backend/data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/api/version"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 15s
