services:
  rotkehlchen-backend:
    build: .
    container_name: rotkehlchen-backend
    ports:
      - "4242:4242"
    volumes:
      - ./data:/data
      - ./logs:/logs
    environment:
      - API_HOST=0.0.0.0
      - API_PORT=4242
      - DATA_DIR=/data
      - CORS_ORIGIN=http://localhost:3000
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:4242/api/1/ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  rotkehlchen-data:
  rotkehlchen-logs: 